#!/usr/bin/env python

import sys

from rqt_auto_trax.auto_trax import AutoTrax
from rqt_gui.main import Main

plugin = 'rqt_auto_trax'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
